# Generated by Django 5.2.5 on 2025-08-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_processingsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
