# Generated by Django 5.2.5 on 2025-08-17 21:01

import django.db.models.deletion
import privacy_engine.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=privacy_engine.storage.EncryptedStorage(), upload_to='protected_files/')),
                ('object_id', models.UUIDField()),
                ('original_filename', models.CharField(help_text='The original name of the file.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
