version: '3.8'

services:
  # Ollama service optimized for Docker performance
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama         # Bind mount from host for better performance
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
    shm_size: 8g                        # Large shared memory for mmap
    ipc: host                           # Share host IPC for performance  
    ulimits:
      memlock: -1                       # Allow memory locking
    security_opt:
      - seccomp:unconfined              # Relax seccomp for mmap syscalls
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '6.0'                   # Increased CPU limit
        reservations:
          memory: 6G
          cpus: '3.0'
    command: ["ollama", "serve"]        # Simple command, no --no-mmap

  # Redis service for Celery
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # PostgreSQL database (production ready)
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: incometax_db
      POSTGRES_USER: incometax_user
      POSTGRES_PASSWORD: incometax_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Django web application
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DEBUG=False
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - DATABASE_URL=postgresql://incometax_user:incometax_password@db:5432/incometax_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - ENCRYPTION_SALT=${ENCRYPTION_SALT}
      - PRIVACY_ENGINE_ENABLED=${PRIVACY_ENGINE_ENABLED}
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    depends_on:
      - db
      - redis
      - ollama
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 incometax_project.wsgi:application"

  # Celery worker for background tasks
  celery:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - DEBUG=False
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - DATABASE_URL=postgresql://incometax_user:incometax_password@db:5432/incometax_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - ENCRYPTION_SALT=${ENCRYPTION_SALT}
      - PRIVACY_ENGINE_ENABLED=${PRIVACY_ENGINE_ENABLED}
    volumes:
      - ./media:/app/media
    depends_on:
      - db
      - redis
      - ollama
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    command: >
      sh -c "python startup_cleanup.py && 
             celery -A incometax_project worker --loglevel=info --pool=solo --concurrency=1 --max-tasks-per-child=1"

  # Celery worker 2 for parallel processing
  celery2:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - DEBUG=False
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - DATABASE_URL=postgresql://incometax_user:incometax_password@db:5432/incometax_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - ENCRYPTION_SALT=${ENCRYPTION_SALT}
      - PRIVACY_ENGINE_ENABLED=${PRIVACY_ENGINE_ENABLED}
    volumes:
      - ./media:/app/media
    depends_on:
      - db
      - redis
      - ollama
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    command: celery -A incometax_project worker --loglevel=info --pool=solo --concurrency=1 --max-tasks-per-child=1

  # Celery worker 3 for parallel processing
  celery3:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - DEBUG=False
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - DATABASE_URL=postgresql://incometax_user:incometax_password@db:5432/incometax_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - ENCRYPTION_SALT=${ENCRYPTION_SALT}
      - PRIVACY_ENGINE_ENABLED=${PRIVACY_ENGINE_ENABLED}
    volumes:
      - ./media:/app/media
    depends_on:
      - db
      - redis
      - ollama
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    command: celery -A incometax_project worker --loglevel=info --pool=solo --concurrency=1 --max-tasks-per-child=1

  # Celery Beat scheduler for periodic tasks
  celery-beat:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./media:/app/media
    depends_on:
      - web
    command: >
      sh -c "rm -f /app/celerybeat.pid &&
             celery -A incometax_project beat --loglevel=info --pidfile=/app/celerybeat.pid"

  # Celery Flower for monitoring (optional)
  flower:
    build: .
    restart: unless-stopped
    ports:
      - "5555:5555"
    env_file: .env
    environment:
      - DEBUG=False
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - DATABASE_URL=postgresql://incometax_user:incometax_password@db:5432/incometax_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    command: celery -A incometax_project flower --port=5555

volumes:
  postgres_data:
  redis_data:
  ollama_data: